##  why  python built in data structures 

#### *To collect multiple data in a structure 

*data structure in python

1.list
2.sets 
3.tuple
4.dictionary - value&key

## 1- list

1.1D
2.Heterogenuos
3.duplicate value
4.indexing - slicing is possible
5.Mutable

In [2]:
empty_cart=[]

In [3]:
empty_cart

[]

In [4]:
type(empty_cart)

list

In [19]:
items_to_buy=["apple","manfo","orange",8.9,9,8]

In [20]:
items_to_buy

['apple', 'manfo', 'orange', 8.9, 9, 8]

In [21]:
type(items_to_buy)

list

In [22]:
len(items_to_buy)

6

In [23]:
items_to_buy[2]#indexing

'orange'

In [24]:
items_to_buy[-2]

9

In [25]:
items_to_buy[-3:-1]

[8.9, 9]

In [26]:
items_to_buy[1]="guva"

In [27]:
items_to_buy

['apple', 'guva', 'orange', 8.9, 9, 8]

In [28]:
items_to_buy.append("Red banana")

In [29]:
items_to_buy

['apple', 'guva', 'orange', 8.9, 9, 8, 'Red banana']

# 2.sets

## 1.1D
2.Heterogeneous
3.it won't allow duplicate values
4.Indexing & slicing is not possible
5.Mutable

In [33]:
empty_cart_2=set()

In [34]:
empty_cart_2

set()

In [35]:
type(empty_cart_2)

set

In [43]:
item_to_buy_2={"apple","manfo","orange",8.9,9,8}

In [55]:
item_to_buy_2

{8, 8.9, 9, 'apple', 'manfo', 'orange'}

In [56]:
item_to_buy_2[1]

TypeError: 'set' object is not subscriptable

In [57]:
item_to_buy_2[2.3]

TypeError: 'set' object is not subscriptable

In [66]:
item_to_buy_2[1]="Red banana"

TypeError: 'set' object does not support item assignment

In [73]:
item_to_buy_2={"apple","manfo","orange",8.9,9,8}

In [74]:
item_to_buy_2

{8, 8.9, 9, 'apple', 'manfo', 'orange'}

In [83]:
items_to_buy_2.add("alva")

In [84]:
items_to_buy_2

{'alva', 'boom'}

In [91]:
items_to_buy_2.discard("alva")

In [92]:
items_to_buy_2

{'boom'}

# 3 - tuple
##

*1 D
*Heterogeneous
*Duplicate values is allowed
*Indexing and slicing also possible
*Immutable

In [93]:
empty_cart_3=()

In [96]:
type (empty_cart_3)

tuple

In [118]:
items_to_buy_3=("apple","manfo","orange",8.9,9,8)

In [119]:
items_to_buy_3

('apple', 'manfo', 'orange', 8.9, 9, 8)

In [120]:
items_to_buy_3[0]

'apple'

In [121]:
items_to_buy_3[0:4]

('apple', 'manfo', 'orange', 8.9)

In [122]:
items_to_buy_3[0]="guva"

TypeError: 'tuple' object does not support item assignment

In [123]:
tuple.

SyntaxError: invalid syntax (1523926194.py, line 1)

In [124]:
items_to_buy_3.count("apple")

1

In [128]:
items_to_buy_3.index("orange")

2

# Dictionary 

it is key value pair

In [129]:
empty_cart_4={}

In [130]:
empty_cart_4

{}

In [131]:
type(empty_cart_4)

dict

In [132]:
student_marks={"maths":98,
              "enl":99,
              "soc":99}

In [134]:
type(student_marks)

dict

In [135]:
items_to_buy_4={"orange":3,"mango":5,"apple":4}

In [136]:
items_to_buy_4

{'orange': 3, 'mango': 5, 'apple': 4}

In [138]:
type(items_to_buy_4)

dict

In [139]:
items_to_buy_4.clear()

In [140]:
items_to_buy_4

{}

In [141]:
items_to_buy_4

{}

In [142]:
items_to_buy_4={"orange":3,"mango":5,"apple":4}
items_to_buy_4

{'orange': 3, 'mango': 5, 'apple': 4}

In [143]:
items_to_buy_4.keys()

dict_keys(['orange', 'mango', 'apple'])

In [144]:
items_to_buy_4.values()

dict_values([3, 5, 4])

In [1]:
items_to_buy_4={"orange":3,"mango":5,"apple":4}
items_to_buy_4

{'orange': 3, 'mango': 5, 'apple': 4}

In [2]:
import pandas as pd

In [7]:
pd.DataFrame(data=items_to_buy_4)

ValueError: If using all scalar values, you must pass an index

## list how it is work in dictionary

In [4]:
math_students_marks={"name":["raj","dee","rahul","gokul","mohan"],
                     "maths":[78,89,99,89,98],
                     "science":[99,89,98,97,96]}

In [5]:
math_students_marks

{'name': ['raj', 'dee', 'rahul', 'gokul', 'mohan'],
 'maths': [78, 89, 99, 89, 98],
 'science': [99, 89, 98, 97, 96]}

In [6]:
pd.DataFrame(data=math_students_marks)

    name  maths  science
0    raj     78       99
1    dee     89       89
2  rahul     99       98
3  gokul     89       97
4  mohan     98       96

## tuple how it is work in dictionary

In [4]:
import pandas as pd

In [21]:
math_students_marks={("eng",89,77,88,68,88),("maths",78,89,99,89,98),("science",99,89,98,97,96)}

In [22]:
math_students_marks

{('eng', 89, 77, 88, 68, 88),
 ('maths', 78, 89, 99, 89, 98),
 ('science', 99, 89, 98, 97, 96)}

In [23]:
pd.DataFrame(data=math_students_marks)

         0   1   2   3   4   5
0    maths  78  89  99  89  98
1      eng  89  77  88  68  88
2  science  99  89  98  97  96

## task -1 set how it's in dictionary

In [20]:
import pandas as pd

In [25]:
math_students_marks={"eng",89,77,88,68,88},{"maths",78,89,99,89,98},{"science",99,89,98,97,96}

In [26]:
math_students_marks

({68, 77, 88, 89, 'eng'},
 {78, 89, 98, 99, 'maths'},
 {89, 96, 97, 98, 99, 'science'})

In [27]:
pd.DataFrame(data=math_students_marks)

     0   1   2      3   4        5
0  eng  68  88     89  77     None
1   98  99  89  maths  78     None
2   96  97  98     99  89  science

In [1]:
list.clear(math_student_marks)

NameError: name 'math_student_marks' is not defined