# Task-1

## 1.list function

In [ ]:
items_to_buy=["mango","apple","orange","banana"]

In [2]:
items_to_buy

['mango', 'apple', 'orange', 'banana']

In [3]:
items_to_buy.append("orange")

In [4]:
items_to_buy

['mango', 'apple', 'orange', 'banana', 'orange']

In [6]:
items_to_buy.clear()

items_to_buy

In [7]:
items_to_buy=["mango","apple","orange","banana"]

In [8]:
items_to_buy

['mango', 'apple', 'orange', 'banana']

In [13]:
items_to_buy.copy()

['mango', 'apple', 'orange', 'banana']

In [14]:
items_to_buy.count("orange")

1

In [15]:
items_to_buy.extend("apple")

In [16]:
items_to_buy

['mango', 'apple', 'orange', 'banana', 'a', 'p', 'p', 'l', 'e']

In [17]:
items_to_buy.index("apple")

1

In [25]:
items_to_buy.insert(8,9)

items_to_buy

In [31]:
items_to_buy.pop(-2)

'e'

In [32]:
items_to_buy.remove("apple")

In [33]:
items_to_buy

['mango', 'orange', 'banana', 'a', 'p', 'p', 'l', 9, 78]

In [43]:
items_to_buy.reverse()

items_to_buy

In [ ]:
items_to_buy.sort()

In [59]:
items_to_buy

['a', 'banana', 'l', 'mango', 'orange', 'p', 'p', 9, 78]

## 2. dictionary function

In [62]:
student_marks={"maths":98,"enl":99,"soc":99}

In [63]:
student_marks

{'maths': 98, 'enl': 99, 'soc': 99}

In [65]:
student_marks.fromkeys("sci",88)

{'s': 88, 'c': 88, 'i': 88}

In [66]:
student_marks.get("maths")

98

In [69]:
student_marks.items()

dict_items([('maths', 98), ('enl', 99), ('soc', 99)])

In [71]:
student_marks.keys()

dict_keys(['maths', 'enl', 'soc'])

In [75]:
student_marks.pop("eng",99)

99

In [77]:
student_marks.popitem()

('soc', 99)

In [79]:
student_marks.setdefault("maths")

98

In [88]:
student_marks.update()

In [89]:
student_marks

{'maths': 98, 'enl': 99}

In [90]:
student_marks.values()

dict_values([98, 99])

## 3 sets function

In [107]:
items_to_buy_3={"apple","manfo","orange",8.9,9,8}

In [108]:
items_to_buy_3

{8, 8.9, 9, 'apple', 'manfo', 'orange'}

In [110]:
items_to_buy_3.add("greens")

In [111]:
items_to_buy_3

{8, 8.9, 9, 'apple', 'greens', 'manfo', 'orange'}

In [112]:
items_to_buy_3.copy()

{8, 8.9, 9, 'apple', 'greens', 'manfo', 'orange'}

In [114]:
items_to_buy_3.difference("orange")

{8, 8.9, 9, 'apple', 'greens', 'manfo', 'orange'}

In [115]:
items_to_buy_3.difference_update("grapes")

In [116]:
item_to_buy_3

{8, 8.9, 9, 'apple', 'banana', 'greens', 'manfo', 'orange', 'red banana'}

In [117]:
items_to_buy_3.discard(8)

In [118]:
items_to_buy_3

{8.9, 9, 'apple', 'greens', 'manfo', 'orange'}

In [125]:
items_to_buy_3.intersection("apple")

set()

In [129]:
items_to_buy_3.isdisjoint("apple")

True

In [133]:
items_to_buy_3.issubset("greens")

False

In [134]:
items_to_buy_3.issuperset("greens")

False

In [136]:
items_to_buy_3.pop()

'greens'

In [138]:
items_to_buy_3.remove(8.9)

In [139]:
items_to_buy_3

{9, 'apple', 'manfo', 'orange'}

In [140]:
items_to_buy_3.symmetric_difference("apple")

{9, 'a', 'apple', 'e', 'l', 'manfo', 'orange', 'p'}

In [141]:
items_to_buy_3.symmetric_difference_update("grrens")

In [142]:
items_to_buy_3

{9, 'apple', 'e', 'g', 'manfo', 'n', 'orange', 'r', 's'}

In [144]:
items_to_buy_3.union("apple")

{9, 'a', 'apple', 'e', 'g', 'l', 'manfo', 'n', 'orange', 'p', 'r', 's'}

In [147]:
items_to_buy_3.update("appless")

In [148]:
items_to_buy_3

{' ',
 9,
 'a',
 'apple',
 'b',
 'd',
 'e',
 'g',
 'l',
 'manfo',
 'n',
 'orange',
 'p',
 'r',
 's'}

# 4 tuple function

In [149]:
items_to_buy_4=("apple","manfo","orange",8.9,9,8)

In [150]:
items_to_buy_4

('apple', 'manfo', 'orange', 8.9, 9, 8)

In [153]:
items_to_buy_4.count("orange")

1

In [156]:
items_to_buy_4.index(8)

5

================================================================================================================

 # Task-2

## 1. list dataframe

In [159]:
import pandas as pd

In [173]:
Food_ball_player={"name":["ronaldo","messi","neymarjr","mbappe","lamine yamal"],
                  "goal r":[99,88,78,89,99],
                  "goal njr":[70,77,79,90,99],
                  "goal mb":[71,79,78,99,99],
                  "goal m":[67,89,99,99,98],
                 "goal ly":[70,60,58,44,50]}

In [174]:
Food_ball_player

{'name': ['ronaldo', 'messi', 'neymarjr', 'mbappe', 'lamine yamal'],
 'goal r': [99, 88, 78, 89, 99],
 'goal njr': [70, 77, 79, 90, 99],
 'goal mb': [71, 79, 78, 99, 99],
 'goal m': [67, 89, 99, 99, 98],
 'goal ly': [70, 60, 58, 44, 50]}

In [175]:
pd.DataFrame(data=Food_ball_player)

           name  goal r  goal njr  goal mb  goal m  goal ly
0       ronaldo      99        70       71      67       70
1         messi      88        77       79      89       60
2      neymarjr      78        79       78      99       58
3        mbappe      89        90       99      99       44
4  lamine yamal      99        99       99      98       50

## 2.sets dataframe

In [176]:
import pandas as pd

In [200]:
Food_ball_player={"ronaldo",99,88,78,89,99},{"neymarjr",70,77,79,90,99},{"mbappe",71,79,78,99,99},{"messi",67,89,99,99,98},{"lamine yanal",70,60,58,44,50}

In [201]:
Food_ball_player

({78, 88, 89, 99, 'ronaldo'},
 {70, 77, 79, 90, 99, 'neymarjr'},
 {71, 78, 79, 99, 'mbappe'},
 {67, 89, 98, 99, 'messi'},
 {44, 50, 58, 60, 70, 'lamine yanal'})

In [202]:
pd.DataFrame(data=Food_ball_player)

              0         1   2   3      4     5
0            99   ronaldo  88  89     78   NaN
1            99  neymarjr  70  90     77  79.0
2        mbappe        99  71  78     79   NaN
3            89        98  67  99  messi   NaN
4  lamine yanal        50  70  58     44  60.0

## 3.tuple dataframe

In [203]:
import pandas as pd

In [206]:
Food_ball_player={("name","ronaldo","messi","neymarjr","mbappe","lamine yamal"),
                  ("goal r",99,88,78,89,99),
                  ("goal njr",70,77,79,90,99),
                  ("goal mb",71,79,78,99,99),
                  ("goal m",67,89,99,99,98),
                 ("goal ly",70,60,58,44,50)}

In [207]:
Food_ball_player

{('goal ly', 70, 60, 58, 44, 50),
 ('goal m', 67, 89, 99, 99, 98),
 ('goal mb', 71, 79, 78, 99, 99),
 ('goal njr', 70, 77, 79, 90, 99),
 ('goal r', 99, 88, 78, 89, 99),
 ('name', 'ronaldo', 'messi', 'neymarjr', 'mbappe', 'lamine yamal')}

In [208]:
pd.DataFrame(data=Food_ball_player)

          0        1      2         3       4             5
0    goal r       99     88        78      89            99
1  goal njr       70     77        79      90            99
2      name  ronaldo  messi  neymarjr  mbappe  lamine yamal
3   goal mb       71     79        78      99            99
4   goal ly       70     60        58      44            50
5    goal m       67     89        99      99            98